pipeline {
    agent any

    environment {
        VENV_DIR = "venv"
        PYTHON = "${env.WORKSPACE}/venv/bin/python"
        PIP = "${env.WORKSPACE}/venv/bin/pip"
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/StefMonnensPXL/dataTest.git', branch: 'main'
            }
        }

        stage('Setup Python Virtual Env') {
            steps {
                sh """
                    python3 -m venv ${VENV_DIR}
                    ${PIP} install --upgrade pip
                    ${PIP} install -r Project/requirements.txt
                    ${PIP} install dvc[s3]
                    # Verify pandas is installed
                    ${PIP} list | grep pandas
                """
            }
        }

        stage('Ingest Data') {
            steps {
                sh """
                    ${PYTHON} Project/ingestion/ingest.py
                """
            }
        }

        stage('Track with DVC') {
            steps {
                sh """
                    # Set the PATH to include virtual environment first
                    export PATH="${env.WORKSPACE}/venv/bin:${PATH}"
                    cd Project
                    ${PYTHON} -m dvc repro dvc.yaml
                    git add dvc.yaml dvc.lock
                    git commit -m "New data ingested with timestamp" || echo "Nothing to commit"
                    git push origin main
                    ${PYTHON} -m dvc push
                """
            }
        }
    }
}