pipeline {
    agent any

    environment {
        VENV_DIR = "venv"
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/StefMonnensPXL/dataTest.git', branch: 'main'
            }
        }

        stage('Setup Python Virtual Env') {
            steps {
                sh """
                    python3 -m venv ${VENV_DIR}
                    source ${VENV_DIR}/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                    pip install dvc[s3]
                """
            }
        }

        stage('Ingest Data') {
            steps {
                sh """
                    source ${VENV_DIR}/bin/activate
                    python ingestion/ingest.py
                """
            }
        }

        stage('Track with DVC') {
            steps {
                sh """
                    source ${VENV_DIR}/bin/activate
                    dvc add data/ metadata/
                    git add data.dvc metadata.dvc
                    git commit -m "New data ingested with timestamp" || echo "Nothing to commit"
                    git push origin main
                    dvc push
                """
            }
        }
    }
}
